services:
  - docker
before_install:
  - docker build -t tsosen/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true tsosen/react-test npm test
after_success:
  - docker build -t tsosen/multi-client ./client
  - docker build -t tsosen/multi-nginx ./nginx
  - docker build -t tsosen/multi-server ./server
  - docker build -t tsosen/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to hub
  - docker push tsosen/multi-client
  #- docker push tsosen/multi-nginx
  #- docker push tsosen/multi-server
  #- docker push tsosen/multi-worker
